steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/smart_hire:latest', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/smart_hire:latest']

  # Step 3: Apply the Cloud Deploy configurations
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['deploy', 'apply', '--file=clouddeploy.yaml', '--region=us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['deploy', 'apply', '--file=dev-target.yaml', '--region=us-central1']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['deploy', 'apply', '--file=prod-target.yaml', '--region=us-central1']

  # Step 4: Deploy to Cloud Deploy pipeline
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - >
       gcloud deploy releases create release-$BUILD_ID
       --delivery-pipeline=smart-hire-pipeline
       --region=us-central1
       --source=./
       --images=smart_hire=gcr.io/$_PROJECT_ID/smart_hire:latest

images:
  - 'gcr.io/$_PROJECT_ID/smart_hire:latest'

options:
  logging: CLOUD_LOGGING_ONLY
