apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-hire-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-hire
  template:
    metadata:
      labels:
        app: smart-hire
    spec:
      containers:
      - name: smart-hire
        image: gcr.io/smarthirehub-429323/smart_hire:latest
        ports:
        - containerPort: 80
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/my_key.json"
        volumeMounts:
        - name: gcp-key
          mountPath: /app/my_key.json
          subPath: my_key.json
      volumes:
      - name: gcp-key
        secret:
          secretName: gcp-key-secret
