apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: dev
description: Development environment
gke:
  cluster: projects/regal-scholar-423322-h0/locations/us-central1-a/clusters/dev-cluster
