apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-hire
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smart-hire
  template:
    metadata:
      labels:
        app: smart-hire
    spec:
      containers:
        - name: smart-hire
          image: gcr.io/$_PROJECT_ID/smart_hire:latest
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: google-application-credentials
                  key: $GOOGLE_APPLICATION_CREDENTIALS
            - name: DB_HOST
              value: $DB_HOST
            - name: DB_NAME
              value: $DB_NAME
            - name: DB_USER
              value: $DB_USER
            - name: DB_PASS
              value: $DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: smart-hire
spec:
  selector:
    app: smart-hire
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
