apiVersion: v1
kind: Service
metadata:
  name: smart-hire-service
spec:
  type: LoadBalancer
  selector:
    app: smart-hire
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
