apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: smart-hire
build:
  artifacts:
    - image: gcr.io/$_PROJECT_ID/smart_hire:latest
deploy:
  kubectl:
    manifests:
      - kubernetes.yaml
profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
          - dev-target.yaml
  - name: prod
    deploy:
      kubectl:
        manifests:
          - prod-target.yaml
