apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_URL
          value: "jdbc:postgresql://34.72.51.3:5432/sonarqube"
        - name: SONARQUBE_JDBC_USERNAME
          value: "postgres"
        - name: SONARQUBE_JDBC_PASSWORD
          value: "Ashu123"
