name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Google Authenticate
        id  : auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set Google Cloud Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Submit Build
        run: gcloud builds submit --config cloudbuild.yaml --substitutions _PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},_SECRET_KEY=${{ secrets.SECRET_KEY }},_DB_HOST=${{ secrets.DB_HOST }},_DB_NAME=${{ secrets.DB_NAME }},_DB_USER=${{ secrets.DB_USER }},_DB_PASS=${{ secrets.DB_PASS }}
