name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: 'latest'

      - name: Create .env file
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > my_key.json

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account storageaccountgcp@regal-scholar-423322-h0.iam.gserviceaccount.com --key-file=my_key.json --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Set Google Cloud Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Submit Build
        run: gcloud builds submit --config cloudbuild.yaml .
