name: Trigger Cloud Build

on:
  push:
    branches:
      - main

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Trigger Cloud Build
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > my_key.json
          gcloud auth activate-service-account --key-file=my_key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud builds submit --config cloudbuild.yaml .
